spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/rss-collection?useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: wsb.team.2021@gmail.com
    password: brzeczyszczekiewicz
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    scheduler:
      persistence:
        enable: false
        redis:
          embedded: false
          enabled: false
